### ISSUE TITLE
Update introrob_py component to python 3 and qt5

### ISSUE THREAD

**Issue by almartinflorido** [JdeRobot/TeachingRobotics#101]

**Comment by jmplaza** [comment]
Maybe we can skip this issue, as introrob_py is no longer the central component for everything. It was, but now the contents of the Teaching Robotics are scattered along several academic components, mainly one per exercise. In fact, we could even delete from the repository. What do you think?

**Comment by almartinflorido** [comment]
Ok, but then what does component we can use to teleoperate ardrone?.  We can use the other components in this repo but some of them are specify for a task.

In any case the changes has been made (minor changes). I'll commit the change if is necessary we can remove the component.

Ok?

**Comment by jmplaza** [comment]
Perfect. 
To teleoperate the ardrone we can use uavviewer, the tool for drones in JdeRobot.

**Comment by almartinflorido** [comment]
Done!
